services:
  status-page:
    image: ghcr.io/energet666/service-status-page-tg:deploy-latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      PUBLIC_BASE_URL: "http://localhost:8080"
      DATA_FILE: /app/data/state.json
      CHECKS_FILE: /app/checks.json
      CHECKS_INTERVAL: "5m"
      BOT_TOKEN: ""
      ADMIN_IDS: ""
    volumes:
      - ./data:/app/data
